---
- name: download from github, set docker-compose, 
  hosts: vm_host
  become: yes

  tasks:
    - name: update and clean
      ansible.builtin.apt: 
        update-cache: true
        upgrade: "yes"
        autoremove: true
        autoclean: true
        clean: true
        cache_valid_time: 1800

    # - name: Pull the alpine image
    #   docker_image:
    #     name: alpine:latest
    #     source: pull
    #     state: present
    
    # - name: Start the alpine container
    #   docker_container:
    #     name: alpine_container
    #     image: alpine:latest
    #     state: started
    #     interactive: yes
    #     command: sh
      
    # - name: navigate to the folder, run docker-compose
    #   ansible.builtin.shell: |
    #     cd /home/steven/docker_SIEM
    #     docker-compose up -d
    #     exit 0